name: Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v3

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run Chrome Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Tests Results
          path: cypress/report
          if-no-files-found: ignore
