name: Cypress Web Workflow

on:
  pull_request:
    branches:
      - main

  workflow_call:
    inputs:
      BROWSER_CHOICE:
        type: string
        required: true
        default: "todos"

  workflow_dispatch:
    inputs:
      TAG:
        required: false
        description: Informe uma TAG para executar os testes - cenário ou suite (AND = '@tagA+tagB', OR = '@tagA @tagB')
        type: string
      BROWSER_CHOICE:
        type: choice
        description: Selecione o browser a ser executado
        options:
          - "chrome"
          - "firefox"
          - "edge"
          - "todos"
        required: true

jobs:
  all_browsers:
    uses: ./.github/workflows/workflow.yml
    if: ${{ github.event.inputs.BROWSER_CHOICE == 'todos' }}
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]
    with:
      TEST_REPOSITORY: github.com/alexander2005rj/cypress-template
      TAG: ${{ inputs.TAG }}
      BROWSER: ${{ matrix.BROWSER || 'chrome' }}

  specific_browser:
    uses: ./.github/workflows/workflow.yml
    if: ${{ github.event.inputs.BROWSER_CHOICE != 'todos' }}
    with:
      TEST_REPOSITORY: github.com/alexander2005rj/cypress-template
      TAG: ${{ inputs.TAG }}
      BROWSER: ${{ matrix.BROWSER || 'chrome' }}
