name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setting Timezone for Brazil
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Sao_Paulo"
          timezoneMacos: "America/Sao_Paulo"
          timezoneWindows: "E. South America Standard Time"

      - name: Checkout Test Repository
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run Chrome Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
          publish-summary: true

      - name: Chrome - Upload Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: cypress/reports
          if-no-files-found: ignore

      - name: Chrome - Upload Snaphosts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Visual Regression
          path: cypress/snapshots
          if-no-files-found: ignore
