name: Workflow

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v3

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run Chrome Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          publish-summary: false

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest
  
      - name: Run Firefox Tests
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
          publish-summary: false

      # - name: Setup Edge
      #   uses: browser-actions/setup-firefox@v1
      #   with:
      #     edge-version: stable
    
      # - name: Run Edge Tests
      #   uses: cypress-io/github-action@v5
      #   with:
      #     browser: edge

      # - name: Setup Webkit
      #   uses: cypress-io/github-action@v5
      #   with:
      #     build: npx playwright install --with-deps webkit
      #     runTests: false

      # - name: Run Webkit Tests
      #   uses: cypress-io/github-action@v5
      #   with:
      #     install: false
      #     start: npx playwright test
      #     browser: webkit
      
      - name: Convert HTML to Markdown
        if: always()
        uses: rknj/html2markdown@v0.1.0
        with:
          html-file: "cypress/report/index.html"
      
      # - name: Test Summary
      #   uses: pcolby/tap-summary@v1
      #   with:
      #     summary-file: path/to/output/file.md
    
      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Tests Results
          path: cypress/report
          if-no-files-found: ignore
