name: Worflow Options

on:
  workflow_call:
    inputs:
      TEST_REPOSITORY:
        required: false
        type: string
        default: ${{ github.repository }}
      TAG:
        type: string
        required: false
      BROWSER:
        type: string
        required: true

jobs:
  run-web-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v3

      - name: Setup Chrome
        if: inputs.BROWSER == 'chrome'
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run Chrome Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          publish-summary: false

      - name: Chrome - Job Summary
        run: |
          SUMMARY="$(cat cypress/reports/summary-chrome.md)"
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      - name: Chrome - Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Chrome - Tests Results
          path: cypress/reports
          if-no-files-found: ignore

      - name: Setup Firefox
        if: inputs.BROWSER == 'firefox'
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Run Firefox Tests
        uses: cypress-io/github-action@v5
        with:
          browser: firefox
          publish-summary: false

      - name: Firefox - Job Summary
        run: |
          SUMMARY="$(cat cypress/reports/summary-firefox.md)"
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      - name: Firefox - Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Firefox - Tests Results
          path: cypress/reports
          if-no-files-found: ignore

      - name: Setup Edge
        if: inputs.BROWSER == 'edge'
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: stable

      - name: Run Edge Tests
        uses: cypress-io/github-action@v5
        with:
          browser: edge
          publish-summary: false

      - name: Edge - Job Summary
        run: |
          SUMMARY="$(cat cypress/reports/summary-edge.md)"
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      - name: Edge - Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Edge - Tests Results
          path: cypress/reports
          if-no-files-found: ignore
