name: Workflow

on: 
  push:
    branches:
      - main

  workflow_call:
    inputs:
      BROWSER_CHOICE:
        type: string
        required: true
        default: 'chrome'
        
  workflow_dispatch:
      inputs:
        BROWSER_CHOICE:
          type: choice
          description: Selecione o browser a ser executado
          options:
            - "chrome"
          required: true

jobs:
  chrome_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v3

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run Chrome Tests
        uses: cypress-io/github-action@v5
        id: chrome
        with:
          browser: chrome
          publish-summary: false
      
      - name: GitHub Actions Job Summary
        uses: x-color/github-actions-job-summary@v0.1.1
        with:
          file: .github/workflows/summary.md
          vars: |
            passed: ${{steps.chrome.outputs.numOfPassed}}
            failed: ${{steps.chrome.outputs.numOfFailed}}
            pendind: ${{steps.chrome.outputs.numOfPending}}
            skipped: ${{steps.chrome.outputs.numOfSkipped}}
            duration: ${{steps.chrome.outputs.durationInMilliseconds}}


         
      # - name: Setup Firefox
      #   uses: browser-actions/setup-firefox@v1
      #   with:
      #     firefox-version: latest
  
      # - name: Run Firefox Tests
      #   uses: cypress-io/github-action@v5
      #   with:
      #     browser: firefox
      #     publish-summary: false
    
      # ==> IMPORTAR AQUI O REPORT GERADO EM TEST_SUMMARY.JS


      # - name: Setup Edge
      #   uses: browser-actions/setup-firefox@v1
      #   with:
      #     edge-version: stable
    
      # - name: Run Edge Tests
      #   uses: cypress-io/github-action@v5
      #   with:
      #     browser: edge
      #     publish-summary: false

      # ==> IMPORTAR AQUI O REPORT GERADO EM TEST_SUMMARY.JS


      # - name: Setup Webkit
      #   uses: cypress-io/github-action@v5
      #   with:
      #     build: npx playwright install --with-deps webkit
      #     runTests: false

      # - name: Run Webkit Tests
      #   uses: cypress-io/github-action@v5
      #   with:
      #     install: false
      #     start: npx playwright test
      #     browser: webkit
      #     publish-summary: false

      # ==> IMPORTAR AQUI O REPORT GERADO EM TEST_SUMMARY.JS
    
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Tests Results
          path: cypress/reports
          if-no-files-found: ignore
