name: Cypress Summary

steps:
  - name: Generating Cypress Results
    run: |
      {
        echo "### Cypress Results"
        echo "| Result                      | Passed :white_check_mark: | Failed :x: | Pending :hand: | Skipped :leftwards_arrow_with_hook: | Duration :clock: |"
        echo "| --------------------------- | ------------------------- | ---------- | -------------- | ----------------------------------- | ---------------- |"
        echo "| Passing :white_check_mark:  |                           |            |                |                                     |                  |"
      } >> $GITHUB_STEP_SUMMARY
