name: Cypress Summary Workflow

on:
  workflow_call:
    inputs:
      BROWSER:
        type: string
        required: true

jobs:
  test-summary:
    runs-on: ubuntu-22.04
    steps:
      - name: Chrome Tests
        run: |
          echo "### Cypress Results"                                                                                                                                                                                                                                                  >> $GITHUB_STEP_SUMMARY
          echo "| Result                      | Passed :heavy_check_mark:               | Failed :x:                              | Pending :hand:                            | Skipped :leftwards_arrow_with_hook:       | Duration :clock8:                                     |"  >> $GITHUB_STEP_SUMMARY
          echo "| ---                         | ---                                     | ---                                     | ---                                       | ---                                       | ---                                                   |"  >> $GITHUB_STEP_SUMMARY
          echo "| Passing :heavy_check_mark:  | ${{steps.headless.outputs.numOfPassed}} | ${{steps.headless.outputs.numOfFailed}} | ${{steps.headless.outputs.numOfPending}}  | ${{steps.headless.outputs.numOfSkipped}}  | ${{steps.headless.outputs.durationInMilliseconds}} ms |"  >> $GITHUB_STEP_SUMMARY
